### PR TITLE
Swap search engine

### PR DESCRIPTION
**Pull request by MRodriguez-M**
Added button next to search bar that allows user to switch between Google and Bing for search results. Addresses issue #14

### CODE REVIEW

**Review by LOGESH-B — COMMENTED** [review]
Hii @MRodriguez-M 
Good Job...
I got an issue
* On initial render it works fine but when I open the inspect tab the ui gets collasped

Before opening the inspect tab loooks good
image

After Openning Inspect tab gets collapsed
image

**Comment by MRodriguez-M** [comment]
What browser are you using? I am trying to replicate this issue but when i open the inspect tab I get no issues with the ui

**Comment by LOGESH-B** [comment]
> What browser are you using? I am trying to replicate this issue but when i open the inspect tab I get no issues with the ui

Chrome browser @MRodriguez-M

**Comment by MRodriguez-M** [comment]
I keep trying to replicate the ui bug by opening the inspect tab with chrome and other browsers but i cannot get it to happen. It could be related to the addition of the icons on the bottom of the page since those were not present in the version of my code in the pull request. I could check with that additional code to possibly replicate and fix the issue but i don't think that code is available on the repo for me to pull.

**Comment by LOGESH-B** [comment]
> I keep trying to replicate the ui bug by opening the inspect tab with chrome and other browsers but i cannot get it to happen. It could be related to the addition of the icons on the bottom of the page since those were not present in the version of my code in the pull request. I could check with that additional code to possibly replicate and fix the issue but i don't think that code is available on the repo for me to pull.

@MRodriguez-M 
You can add a quick link by clicking the + button on bottom
You supposed to provide the logo link and title

**Comment by MRodriguez-M** [comment]
I checked again to see if i could replicate the issue after adding a quick link and opening the inspect panel:

This is before opening the inspect panel:
before-inspect

This is after closing the inspect panel:
after-inspect

There is no change in the UI on my end. What steps did you take exactly to cause this issue? What quick links did you create? Does the issue occur if you do not add quick links? Are you able to replicate the bug every time you try?

**Review by LOGESH-B — APPROVED** [review]
Hii @MRodriguez-M 
Thanks for your contribution....
The issue I don't know but only on my google account it creating issue, in other chrome account and other browsers it works fine

**Pull request merged**
