### PR TITLE
Button and form adjustment 

### PR DESCRIPTION
**Pull request by Tioluwanilowo**
1. switch the plus button to the top
2. moved the form to the bottom

### CODE REVIEW

**Comment by Tioluwanilowo** [comment]
@LOGESH-B  this is the adjusted PR

**Review by LOGESH-B — CHANGES_REQUESTED** [review]
Hii @Tioluwanilowo 
Thanks for your contribution.

The Quick links are gone beyond the screen and add is not visible
image

image

image

🔴Please add a quick link and try on your local machine

**Comment by Tioluwanilowo** [comment]
this what it looks like on my end 
image

**Comment by LOGESH-B** [comment]
> this what it looks like on my end image

1) If the forms are came to down means ,then the quick links may not be visible 
2) I can't find the Add button on screen
3) Add Quick Link wheather you can see are not.On my side I have the Quick link but it is not visible on the screen but rendered on the DOM

**Important Note:**
🔴 1st create a issue then get confirmation from the mainteners to work on that issue,if you work directly then the suggestions from the project mainteners may not received by you and your work may gone unused✌️

**Comment by LOGESH-B** [comment]
Hii @Tioluwanilowo 
You can find any other issue and work on that,for now it is not that much important

**Review by LOGESH-B — COMMENTED** [review]
Hii @Tioluwanilowo 
Great work🙌

But the UI we Planned as like mac/windows
* Your design is changing the entire idea

**Requesting you to get the approval before getting into it**

I am waiting for your reply before closing this PR.Do Reply

You can look into the other issues and work on that 
**Happy coding🙌**

**Comment by Tioluwanilowo** [comment]
image
@LOGESH-B it should look like this now

**Comment by LOGESH-B** [comment]
Hii @Tioluwanilowo 
Please read this


> Hii @Tioluwanilowo Great work🙌
> 
> But the UI we Planned as like mac/windows
> 
> * Your design is changing the entire idea
> 
> **Requesting you to get the approval before getting into it**
> 
> I am waiting for your reply before closing this PR.Do Reply
> 
> You can look into the other issues and work on that **Happy coding🙌**

**Comment by Tioluwanilowo** [comment]
> Hii @Tioluwanilowo Great work🙌
> 
> But the UI we Planned as like mac/windows
> 
> * Your design is changing the entire idea
> 
> **Requesting you to get the approval before getting into it**
> 
> I am waiting for your reply before closing this PR.Do Reply
> 
> You can look into the other issues and work on that **Happy coding🙌**

If you want the list at the bottom I will advise you to separate the li for the + button in other to make it responsive on all devices since both the li and + button are under the same li

**Comment by LOGESH-B** [comment]
> > Hii @Tioluwanilowo Great work🙌
> > But the UI we Planned as like mac/windows
> > 
> > * Your design is changing the entire idea
> > 
> > **Requesting you to get the approval before getting into it**
> > I am waiting for your reply before closing this PR.Do Reply
> > You can look into the other issues and work on that **Happy coding🙌**
> 
> If you want the list at the bottom I will advise you to separate the li for the + button in other to make it responsive on all devices since both the li and + button are under the same li

Yeah @Tioluwanilowo  Initially I was also assuming the same ,but you moved entier  thing to top and bring the form to bottom

So now you can **rework** on that and move the Add button alone to the top not anything else

🔴Make sure you tested locally with adding new quick link

Thanks for your contribution

**Comment by Tioluwanilowo** [comment]
just to confirm i should bring the form back to the bottom and leave the add button at the top.

**Comment by LOGESH-B** [comment]
> just to confirm i should bring the form back to the bottom and leave the add button at the top.

@Tioluwanilowo 
My suggestion is to keep everything as it is expect the add button,because if the form came to bottom ..the bottom area becomes conjusted with the Quick links

**Comment by Tioluwanilowo** [comment]
The add button is attached to your quick link, so if you want it to stand alone you have to separate the add button into a different div from your html and js. and if you do not want it to be separated then the quick link and add bottom will be returned to the bottom while the form remains on top.

**Comment by LOGESH-B** [comment]
> The add button is attached to your quick link, so if you want it to stand alone you have to separate the add button into a different div from your html and js. and if you do not want it to be separated then the quick link and add bottom will be returned to the bottom while the form remains on top.


Yeah exactly @Tioluwanilowo ,I suggest you to keep everything as it is and move the add btn alone to top right,because the layout at present is allset.In feature we make the quick links at bottom scrollable

**Comment by Tioluwanilowo** [comment]
For me to make the + stand alone then you have to adjust it from your HTML yourself or else i have to rewrite it myself because in your code you joined + and li in one element which is in the div with the class bottom.

**Comment by LOGESH-B** [comment]
Hi @Tioluwanilowo 
If you are interested you can do...otherwise we want to wait for sometime to do this..

**Comment by Tioluwanilowo** [comment]
I can't see a comment on the js file so I don't understand how the + icon got to the web because I can't trace it. Since I can't trace how exactly the button gets there how would you let me leave the changes?

**Comment by LOGESH-B** [comment]
Hii @Tioluwanilowo 
At line no 10 i am appending the add but as a last li and every onload fuc

**Comment by LOGESH-B** [comment]
Hiii @Tioluwanilowo 
I can't able to get you.....now what i supposed to do?

**Comment by Tioluwanilowo** [comment]
looking at the current changes that I have made what is the adjustment you need?

**Comment by LOGESH-B** [comment]
Hii @Tioluwanilowo 
Can you able to move that add button alone to the top right corner...if it is done means we can make the quick links at bottom scrollable and responsive


Sorry for this much conversation about this PR....this is because we planned to having the quick links at the bottom but you changed the theme of the layout that's why it takes long conversation

**Comment by Tioluwanilowo** [comment]
done

**Review by LOGESH-B — CHANGES_REQUESTED** [review]
Hii @Tioluwanilowo 
Please try to understand what's I am telling
* Only the add button move to top
* quick links needs to be placed at bottom

Only add button
image

**Comment by Tioluwanilowo** [comment]
it can't be separated from the quick link, if you check your HTML code the + icon is combined with your quick link you didn't create a separate div for it. So if I move the + icon it also affects the quick link

**Comment by LOGESH-B** [comment]
> it can't be separated from the quick link, if you check your HTML code the + icon is combined with your quick link you didn't create a separate div for it. So if I move the + icon it also affects the quick link

@Tioluwanilowo 
I Think it cannot affect the quick link because in line 10 we appending the button to the li list.....if we remove that it cannot cause any effect I think so

**Pull request closed without merging**
