### PR TITLE
gitHubButton added

### PR DESCRIPTION
**Pull request by jaKasienka**

### CODE REVIEW

**Review by LOGESH-B — CHANGES_REQUESTED** [review]
Hii @jaKasienka 
Now it looks not very well....Can you place the github logo alone at the left bottom cornor.... without any name

**Comment by jaKasienka** [comment]
Hi @LOGESH-B! yes, I'll change it

**Comment by jaKasienka** [comment]
i hope this will do it!

**Review by LOGESH-B — APPROVED** [review]
Hii @jaKasienka 
Thaks for your contribution
Tested Locally Approved for merge

**Pull request merged**
