### PR TITLE
changes done

### PR DESCRIPTION
**Pull request by HamzaFarooqArif**
Added date and time on the landing page. it will get auto-refresh after every minute

### CODE REVIEW

**Review by LOGESH-B — COMMENTED** [review]
Great job @HamzaFarooqArif ,
image

I want small changes 
* Reduce the Font size and made some space between the searchbar and the date and time
* Also try to add linear gradient ofor the text
Group 1
Refer the UI

**Comment by HamzaFarooqArif** [comment]
requested changes done. please review again

**Review by LOGESH-B — COMMENTED** [review]
Hii @HamzaFarooqArif 🙌
Yeah Looks nice ,can you make the search bar center of the page and the date and time above the  search bar as like now

**Comment by HamzaFarooqArif** [comment]
search-bar centered. please review again

**Review by LOGESH-B — APPROVED** [review]
Changes Accepted @HamzaFarooqArif

**Pull request merged**
